/**
 * Build Script for YouTube Time Tracker
 * 
 * Concatenates all JS source files from src/ into dist/content.js
 * in the correct dependency order.
 * 
 * Usage: node build.js
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'content.js');

// Files in dependency order (later files can reference earlier ones)
const JS_FILES = [
    // 1. Shared: state, constants, utilities
    'shared/state.js',
    'shared/constants.js',
    'shared/utils.js',
    'shared/modal-utils.js',

    // 2. Shorts Blocker domain
    'shorts-blocker/blocker.js',
    'shorts-blocker/mocking-screen.js',

    // 3. Stats Tracker domain
    'stats-tracker/tracking.js',
    'stats-tracker/sidebar-template.js',
    'stats-tracker/sidebar-events.js',
    'stats-tracker/sidebar-ui.js',
    'stats-tracker/history-render.js',
    'stats-tracker/analytics-render.js',

    // 4. Break Reminder domain
    'break-reminder/reminder.js',

    // 5. Initialization (must be last)
    'init/bootstrap.js',
];

// Ensure dist directory exists
if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
}

// Concatenate all files
let output = '// Auto-generated by build.js — do not edit directly\n';
output += `// Built at: ${new Date().toISOString()}\n\n`;

for (const file of JS_FILES) {
    const filePath = path.join(SRC_DIR, file);
    
    if (!fs.existsSync(filePath)) {
        console.error(`ERROR: Missing file: ${filePath}`);
        process.exit(1);
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    output += `// ─── ${file} ${'─'.repeat(Math.max(0, 60 - file.length))} \n`;
    output += content;
    output += '\n\n';
}

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

// Print summary
const stats = fs.statSync(OUTPUT_FILE);
console.log(`\n✅ Build complete: dist/content.js`);
console.log(`   Size: ${(stats.size / 1024).toFixed(1)} KB`);
console.log(`   Files: ${JS_FILES.length} source files concatenated\n`);

// Verify line counts of source files
console.log('📊 Source file line counts:');
let hasOversize = false;
for (const file of JS_FILES) {
    const filePath = path.join(SRC_DIR, file);
    const lines = fs.readFileSync(filePath, 'utf-8').split('\n').length;
    const status = lines > 300 ? '⚠️  OVER 300' : '✓';
    if (lines > 300) hasOversize = true;
    console.log(`   ${status} ${file}: ${lines} lines`);
}

if (hasOversize) {
    console.log('\n⚠️  Some files exceed 300 lines!');
} else {
    console.log('\n✅ All source files are within the 300-line limit.');
}
