/**
 * Build Script for AI Color Theme Picker
 * 
 * Concatenates all JS source files from src/ into dist/popup.js
 * in the correct dependency order.
 * 
 * Usage: node build.js
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'popup.js');

// Files in dependency order
const JS_FILES = [
    'shared/icons.js',
    'shared/utils.js',
    'popup/state.js',
    'popup/ui.js',
    'popup/api-keys.js',
    'popup/generator.js',
    'popup/init.js',
];

// Ensure dist directory exists
if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
}

// Concatenate all files
let output = '// Auto-generated by build.js — do not edit directly\n';
output += `// Built at: ${new Date().toISOString()}\n\n`;

for (const file of JS_FILES) {
    const filePath = path.join(SRC_DIR, file);
    
    if (!fs.existsSync(filePath)) {
        console.error(`ERROR: Missing file: ${filePath}`);
        process.exit(1);
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    output += `// ─── ${file} ${'─'.repeat(Math.max(0, 60 - file.length))} \n`;
    output += content;
    output += '\n\n';
}

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

console.log(`\n✅ Build complete: dist/popup.js`);
const stats = fs.statSync(OUTPUT_FILE);
console.log(`   Size: ${(stats.size / 1024).toFixed(1)} KB`);
console.log(`   Files: ${JS_FILES.length} source files concatenated\n`);
